//Shared between cpp and glsl files
//GBuffer output binding

#define GBUFFER_INPUT_POSITION 0
#define GBUFFER_INPUT_UV0 1
#define GBUFFER_INPUT_NORMAL 2
#define GBUFFER_INPUT_TANGENT 3
#define GBUFFER_INPUT_BITANGENT 4

#define GBUFFER_OUTPUT_NORMAL 0
#define GBUFFER_OUTPUT_ALBEDO 1
#define GBUFFER_OUTPUT_ROUGHNESS_METALLIC_REFLECTABLE 2
#define GBUFFER_OUTPUT_VELOCITY 3

//GBuffer shading texture binding
#define LIGHTING_TEX_GBUFFER_NORMAL 0
#define LIGHTING_TEX_GBUFFER_ALBEDO 1
#define LIGHTING_TEX_GBUFFER_ROUGHNESS_METALLIC_REFLECTABLE 2
#define LIGHTING_TEX_GBUFFER_DEPTH 3
#define LIGHTING_TEX_AO 4
#define LIGHTING_TEX_SHADOWMAP 10
#define LIGHTING_TEX_SHADOWCUBEMAP 11

